# metamodel_version: 1.7.0# version: 3.2.3id: retrieval_source
schema_generating: true
description: Provides information about how a particular InformationResource served
  as a source from which knowledge expressed in an Edge, or data used to generate
  this knowledge, was retrieved.
display_name: retrieval source
document_category: retrieval source
weight: 20
fields:
- id: id
  description: A unique identifier for an entity. Must be either a CURIE shorthand
    for a URI or a complete URI
  display_name: id
- id: iri
  description: An IRI for an entity. This is determined by the id using expansion
    rules.
  display_name: iri
- id: type
  display_name: type
  cardinality: multi
- id: name
  description: A human-readable name for an attribute or entity.
  display_name: name
- id: description
  description: a human-readable description of an entity
  display_name: description
- id: has_attribute
  description: connects any entity to an attribute
  display_name: has attribute
  cardinality: multi
- id: provided_by
  description: The value in this node property represents the knowledge provider that
    created or assembled the node and all of its attributes.  Used internally to represent
    how a particular node made its way into a knowledge provider or graph.
  display_name: provided by
  cardinality: multi
- id: category
  description: "Name of the high level ontology class in which this entity is categorized.\
    \ Corresponds to the label for the biolink entity type class.\n * In a neo4j database\
    \ this MAY correspond to the neo4j label tag.\n * In an RDF database it should\
    \ be a biolink model class URI.\nThis field is multi-valued. It should include\
    \ values for ancestors of the biolink class; for example, a protein such as Shh\
    \ would have category values `biolink:Protein`, `biolink:GeneProduct`, `biolink:MolecularEntity`,\
    \ ...\nIn an RDF database, nodes will typically have an rdf:type triples. This\
    \ can be to the most specific biolink class, or potentially to a class more specific\
    \ than something in biolink. For example, a sequence feature `f` may have a rdf:type\
    \ assertion to a SO class such as TF_binding_site, which is more specific than\
    \ anything in biolink. Here we would have categories {biolink:GenomicEntity, biolink:MolecularEntity,\
    \ biolink:NamedThing}"
  display_name: named thing_category
  cardinality: multi
- id: license
  display_name: license
- id: rights
  display_name: rights
- id: format
  display_name: format
- id: creation_date
  description: date on which an entity was created. This can be applied to nodes or
    edges
  display_name: creation date
- id: resource
  description: The CURIE for an Information Resource that served as a source of knowledge
    expressed in an Edge, or a source of data used to generate this knowledge.
  display_name: resource
- id: resource_role
  description: The role played by the InformationResource in serving as a source for
    an Edge. Note that a given Edge should have one and only one 'primary' source,
    and may have any number of 'aggregator' or 'supporting data' sources.
  display_name: resource role
- id: upstream_resources
  description: An upstream InformationResource from which the resource being described
    directly retrieved a record of the knowledge expressed in the Edge, or data used
    to generate this knowledge. This is an array because there are cases where a merged
    Edge holds knowledge that was retrieved from multiple sources. e.g. an Edge provided
    by the ARAGORN ARA can expressing knowledge it retrieved from both the automat-mychem-info
    and molepro KPs, which both provided it with records of this single fact.
  display_name: upstream resources
- id: xref
  description: Alternate CURIEs for a thing
  display_name: xref
  cardinality: multi
